apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: citm
  annotations:
    config.kubernetes.io/local-config: "true"
helmCharts:
- chartArgs:
    name: citm-server
    version: 1.22.0
    repo: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
  templateOptions:
    releaseName: citm
    namespace: citm
    valuesInline:
      httpServer:
        resources:
          requests:
            memory: 120Mi
            cpu: 120m
            ephemeral-storage: 120Mi
