# Source: citm-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: citm-server
    chart: citm-server-1.22.0
    component: "citm-server"
    heritage: Helm
    release: citm
    helm.sh/chart: citm-server-1.22.0
    app.kubernetes.io/name: citm-server
    app.kubernetes.io/instance: citm
    app.kubernetes.io/component: MessagingAndProtocols
    app.kubernetes.io/version: "1.22.0-1.0.3.0-rocky8"
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/part-of: "citm"
  name: citm-citm-server
  namespace: citm
spec:
  ports:
  - name: "tcp-http-8080-citm-server"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: citm-server
    component: "citm-server"
    release: citm
  type: "ClusterIP"
