# ./base/kustomization.yaml
helmCharts:
- name: csf-testapp-hello-world
  repo: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
  version: 1.0.4
  releaseName: app
  namespace: cert-manager
  valuesInline:
    ingress:
      enabled: "false"
