# ./base/kustomization.yaml
helmCharts:
- name: cert-manager-crds
  repo: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
  version: 2.0.6
  releaseName: cm-crds
  namespace: cert-manager
- name: cert-manager
  repo: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
  version: 2.0.9
  releaseName: cm
  namespace: cert-manager
