apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: example/default
  name: default
  namespace: demons
  annotations:
    internal.kpt.dev/upstream-identifier: '|ResourceQuota|example|default'
  labels:
    environment: demo
spec:
  hard:
    cpu: "40"
    memory: 40G
