apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bikes.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - brand
              - model
              properties:
                category:
                  type: string
                  pattern: "road|mountain|city|electric"
                  default: "road"
                brand:
                  type: string
                model:
                  type: string
                year:
                  type: integer
                  default: 2022
                weight:
                  type: string
                  pattern: "\d+\.?\d*"
                  default: "10.0"
  scope: Namespaced
  names:
    plural: bikes
    singular: bike
    kind: Bike
