apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quasars.eso.org
spec:
  scope: Namespaced
  names:
    plural: quasars
    singular: quasar
    kind: Quasar
  group: eso.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - name
              - constellation
              properties:
                name:
                  type: string
                constellation:
                  type: string
                type:
                  type: string
                redshift:
                  type: string
                  pattern: '\d+\.?\d*'
                apparentMagnitude:
                  type: string
                  pattern: '\d+\.?\d*'
                discoveryYear:
                  type: integer
