apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: cert-sync
  namespace: cert-manager
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/philippart/kpt-demo/
    branch: main
    dir: cert-manager
    auth: token
    proxy: http://135.245.192.7:8000
    secretRef:
      name: gh-creds
