apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: minecraft
helmCharts:
- chartArgs:
    name: minecraft
    version: 3.1.3
    repo: https://itzg.github.io/minecraft-server-charts
  templateOptions:
    releaseName: test
    namespace: minecraft
